Commuter Patterns: Make border nodes more visible
Problems with previous border intersections:
- too small to meaningfully compare heatmap colors
- hard to hover/click
- hard to read overlayed label from https://github.com/dabreegster/abstreet/pull/235
- hard to read overlayed borders for selection/hover state

I initially tried it with a Circle, which I personally though looked a
little better, but you cannot add a border to a circle.polygon due to
error: "Can't make a ring with mismatching first/last points"